# .github/FUNDING.yml
# Этот файл должен быть именно в такой папке и с таким названием!

github: [NormikChel, Normik-Chel] # Оставил один аккаунт, уточни, если нужны оба.
patreon: NormikChel
buy_me_a_coffee: normikchel
ko_fi: normikchel # Добавил Ko-fi, раз уж есть BMAC, это аналог.
custom:
  - "https://www.donationalerts.com/r/normik_chel"
  - "http://boosty.to/NormikChel/donate"
  - "https://new.donatepay.ru/@NormikChel"
  - "https://memealerts.com/NormikChel"
